version: 0.2

phases: # 각 명령을 실행하도록 codebuild를 지시할 수 있는 빌드 단계를 나타냅니다
  pre_build: #빌드 하기전 client 로 들어가서 -> npm i로 혹시모를 package 설치 대비
    commands:
      - cd client
      - npm install
  build:
    commands:
      -npm run build
artifacts:#
  files:
    -'**/*'
  base-directory: client/build